const situations = [
    `The Magician represents manifestation, power, and mastery. Its presence suggests a situation where you have the ability to create and influence outcomes. You possess the necessary skills and resources to achieve success. Harness your creativity and take inspired action to bring your desires into reality. Trust in your abilities and embrace the opportunity to make things happen.`,
    `Temperance represents balance, harmony, and moderation. Its presence suggests a situation where finding a middle ground and maintaining equilibrium is crucial. It advises you to seek harmony between different aspects of your life and find a balanced approach. Embrace patience, adaptability, and compromise to navigate challenges successfully. By staying centered and finding a harmonious flow, you can bring stability and peace to the situation.`,
    `The Chariot represents determination, willpower, and forward movement. Its presence suggests a situation where you have the strength and motivation to overcome obstacles and achieve your goals. Embrace your inner drive and take charge of the situation with confidence. Harness your focus and determination to propel yourself towards success. Trust in your abilities and navigate any challenges with resilience to reach your desired outcome.`,
    `The Devil represents temptation, bondage, and illusions. Its presence suggests a situation where you may be entangled in unhealthy patterns or negative influences. It warns against giving in to temptation or being trapped by limiting beliefs. Take caution and break free from destructive cycles to regain control. By recognizing the illusions and seeking liberation, you can overcome obstacles and find a path towards empowerment and freedom.`,
    `The Fool represents new beginnings, spontaneity, and taking leaps of faith. Its presence suggests a situation where you are embarking on a fresh journey or venture. Embrace the unknown with open-mindedness and optimism. Trust your instincts and take bold, courageous steps forward. Embrace the joy of exploration and embrace the opportunities that come your way.`,
    `The Hermit represents introspection, solitude, and inner wisdom. Its presence suggests a situation where taking time for self-reflection and seeking solitude is beneficial. Embrace moments of solitude and quiet introspection to gain deeper insights. Trust in your inner wisdom and follow your own path. By seeking solitude and inner guidance, you will find the answers you seek and navigate the situation with clarity.`,
    `The Moon represents intuition, emotions, and hidden aspects. Its presence suggests a situation where there may be uncertainty or confusion. Trust your intuition and inner guidance to navigate through the shadows. Embrace the mysteries and delve deeper to uncover hidden truths. By embracing the power of your emotions and intuition, you will gain clarity and find your way forward in the situation.`,
    `The Sun represents joy, positivity, and success. Its presence suggests a situation where you can expect an abundance of light and positivity. Embrace the energy of optimism and let it guide you towards a favorable outcome. Bask in the warmth of success and allow your inner light to shine brightly. Trust in the process and enjoy the journey towards a fulfilling result.`,
    `The Tower represents sudden change, upheaval, and transformation. Its presence suggests a situation where existing structures may crumble, creating chaos and uncertainty. Embrace the opportunity for growth and release attachment to what no longer serves you. Embrace the rebuilding process and trust that from the rubble, a stronger foundation will emerge. Embrace the transformative power of the Tower and allow it to lead you to a more authentic and aligned path.`,
]

const challenges = [
    `The Magician represents manifestation, power, and mastery. Its presence suggests a challenge where harnessing your inner resources and abilities is necessary. You are being called to tap into your creativity and confidence to overcome obstacles. Embrace your skills and take intentional action to transform the situation. By utilizing your personal power and aligning your intentions, you can conquer the challenge and achieve success.`,
    `Temperance represents balance, harmony, and moderation. Its presence suggests a challenge where finding equilibrium and maintaining inner peace is essential. Embrace the need for patience and moderation as you navigate conflicting elements. Seek harmony and compromise to overcome obstacles and find a balanced solution. By embracing a balanced approach and seeking harmony within, you can successfully navigate the challenge and find a favorable outcome.`,
    `The Chariot represents determination, willpower, and forward movement. Its presence suggests a challenge that requires taking charge and harnessing your inner strength. Embrace the need for focused action and assertiveness to overcome obstacles. Stay disciplined and navigate through any adversities with confidence and resilience. By harnessing your determination and maintaining a clear direction, you can conquer the challenge and achieve victory.`,
    `The Devil represents temptation, bondage, and illusions. Its presence suggests a challenge where you may be confronted with destructive patterns or negative influences. Beware of the illusions that can hold you back and keep you trapped. Break free from limiting beliefs and unhealthy attachments to overcome the challenge. By recognizing the shadows and embracing liberation, you can conquer the challenge and find a path towards personal empowerment.`,
    `The Fool represents new beginnings, spontaneity, and taking leaps of faith. Its presence suggests a challenge where stepping into the unknown is required. Embrace the uncertainty and trust in your instincts as you navigate through unfamiliar territory. Embrace the lessons and growth that come with embracing the unknown. By embracing your inner adventurer and taking bold risks, you can overcome the challenge and discover new opportunities along the way.`,
    `The Hermit represents introspection, solitude, and inner wisdom. Its presence suggests a challenge that calls for deep reflection and inner guidance. Embrace the need for solitude and introspection to find clarity amidst confusion. Trust in your inner wisdom and seek answers within yourself. By embracing the wisdom gained through introspection, you can overcome the challenge and find a path forward.`,
    `The Moon represents intuition, emotions, and hidden aspects. Its presence suggests a challenge where navigating through uncertainty and facing fears is required. Embrace the power of your intuition and trust your inner guidance to find clarity amidst the shadows. Explore the depths of your emotions and face the hidden truths that arise. By embracing the mystery and harnessing your inner strength, you can overcome the challenge and find illumination in the darkness.`,
    `The Sun represents joy, positivity, and success. Its presence suggests a challenge where maintaining a positive mindset and embracing optimism is crucial. Embrace the power of positivity and let it guide you through obstacles. Tap into your inner light and radiate confidence and happiness. By embracing the energy of the Sun, you can overcome the challenge and bask in the warmth of success.`,
    `The Tower represents sudden change, upheaval, and disruption. Its presence suggests a challenge where existing structures or beliefs may crumble. Embrace the opportunity for transformation and release attachment to what no longer serves you. Through surrendering to change and embracing the lessons it brings, you can find new strength and rebuild from the ground up. Embrace the potential for growth and trust that from the chaos, a stronger foundation will emerge.`,
]

export { situations, challenges }