// Yes Cards
const yesCards = [
    'The cards dance in unison, heralding a resounding "yes" to your question. This is a time of alignment, where the universe echoes your intentions and desires. The cosmic forces are conspiring in your favor, creating a fertile ground for success and fulfillment. Embrace the synchronicities and seize the opportunities that unfold before you. Trust in your intuition and let it guide you towards the realization of your dreams. The journey ahead is adorned with triumph and abundant blessings.',
    'The cards paint a vivid tableau of affirmation, illuminating the path with a brilliant "yes." You are cocooned in a tapestry of auspicious energies, signaling a period of expansion and prosperity. Your perseverance, dedication, and positive mindset have aligned the stars in your favor. This is a time to soar, to embrace the limitless possibilities that lie within your reach. Allow the currents of serendipity to carry you towards the destination of your dreams.',
    'The oracle cards speak with resounding certainty, revealing a tapestry of radiant possibilities and answering your question with a heartfelt "yes." The cosmic symphony is in perfect harmony, aligning circumstances, and energies to support your aspirations. This is a moment of divine intervention, where the universe conspires to bring you joy and fulfillment. Trust in the whispers of the cosmos, for they hold the keys to unlocking the doors of abundance and transformation.',
    'The cards have cast their spell, unraveling a tale of affirmation and granting your question a resounding "yes." The currents of fate are guiding you towards a destination bathed in light and promise. Opportunities abound, and the universe beckons you to embrace the adventure that awaits. Trust in your innate wisdom, for it has brought you to this moment of delightful affirmation. Open your heart to receive the blessings and let the journey unfold with grace and serendipity.',
    'The cards stand as beacons of encouragement, declaring a definitive "yes" to your query. The cosmos is conspiring in your favor, weaving a tapestry of serendipitous events and aligning the energies to manifest your desires. This is a time of abundant growth, where dreams have the power to materialize. Embrace the wave of positivity and seize the opportunities that come your way. Trust in the inherent magic that resides within you, for it holds the key to unlocking a world of limitless possibilities.'
  ];
  
  // No Cards
  const noCards = [
    'The cards reveal a discordant note, suggesting a negative outcome to your question. It is essential to acknowledge the hurdles or challenges that currently impede your progress. Take a moment to reassess your approach and realign your intentions. Remember, a "no" from the cards is not an outright rejection but an invitation to explore different avenues and gain a deeper understanding. Embrace this moment of reflection and let it be the catalyst for growth and transformation.',
    'The cards foretell a detour on your path, indicating a negative outcome to your query. It is important to heed this message and proceed with caution. The currents of the universe are nudging you to pause, reevaluate, and consider alternative routes. Although the answer may be unfavorable, it holds within it the seeds of opportunity. Embrace the lessons embedded in this setback and let them shape a more resilient and informed future. Trust in your ability to navigate the ebbs and flows of life.',
    'The cards have revealed a landscape painted with caution and restraint, indicating a probable negative outcome. It is essential to accept the current limitations and recalibrate your expectations accordingly. This period serves as a valuable lesson in patience and adaptability. Embrace the transformative power of resilience and seek alternative paths that align',
    'The cards whisper a gentle "no" in response to your question. It is a moment of redirection, urging you to reassess your current path. The universe is nudging you to pause, reflect, and realign your intentions. Although the answer may be disappointing, it holds within it the seeds of growth and wisdom. Embrace this moment as an opportunity to gain clarity, make necessary adjustments, and explore new possibilities. Trust that by honoring this message, you will uncover hidden blessings and forge a path that aligns with your highest good.',
    'The cards cast shadows upon the canvas, revealing a negative outcome to your query. It is a time of introspection and recalibration. Embrace this moment as a catalyst for growth and self-discovery. The universe invites you to release attachments to outcomes and surrender to the natural ebb and flow of life. While the answer may be disheartening, it opens the door for new perspectives and fresh beginnings. Trust that by navigating this period with grace and resilience, you will find renewed clarity and navigate towards a more aligned path.'
  ];
  
  // Export the Yes and No cards
  export { yesCards, noCards };
  