// Yes Cards
const yesCards = [
    'The cards dance in unison, heralding a resounding "yes" to your question. This is a time of alignment, where the universe echoes your intentions and desires. The cosmic forces are conspiring in your favor, creating a fertile ground for success and fulfillment. Embrace the synchronicities and seize the opportunities that unfold before you. Trust in your intuition and let it guide you towards the realization of your dreams. The journey ahead is adorned with triumph and abundant blessings.',
    'The cards paint a vivid tableau of affirmation, illuminating the path with a brilliant "yes." You are cocooned in a tapestry of auspicious energies, signaling a period of expansion and prosperity. Your perseverance, dedication, and positive mindset have aligned the stars in your favor. This is a time to soar, to embrace the limitless possibilities that lie within your reach. Allow the currents of serendipity to carry you towards the destination of your dreams.',
    'The oracle cards speak with resounding certainty, revealing a tapestry of radiant possibilities and answering your question with a heartfelt "yes." The cosmic symphony is in perfect harmony, aligning circumstances, and energies to support your aspirations. This is a moment of divine intervention, where the universe conspires to bring you joy and fulfillment. Trust in the whispers of the cosmos, for they hold the keys to unlocking the doors of abundance and transformation.',
    'The cards have cast their spell, unraveling a tale of affirmation and granting your question a resounding "yes." The currents of fate are guiding you towards a destination bathed in light and promise. Opportunities abound, and the universe beckons you to embrace the adventure that awaits. Trust in your innate wisdom, for it has brought you to this moment of delightful affirmation. Open your heart to receive the blessings and let the journey unfold with grace and serendipity.',
    'The cards stand as beacons of encouragement, declaring a definitive "yes" to your query. The cosmos is conspiring in your favor, weaving a tapestry of serendipitous events and aligning the energies to manifest your desires. This is a time of abundant growth, where dreams have the power to materialize. Embrace the wave of positivity and seize the opportunities that come your way. Trust in the inherent magic that resides within you, for it holds the key to unlocking a world of limitless possibilities.'
  ];
  
  // No Cards
  const noCards = [
    'The cards reveal a discordant note, suggesting a negative outcome to your question. It is essential to acknowledge the hurdles or challenges that currently impede your progress. Take a moment to reassess your approach and realign your intentions. Remember, a "no" from the cards is not an outright rejection but an invitation to explore different avenues and gain a deeper understanding. Embrace this moment of reflection and let it be the catalyst for growth and transformation.',
    'The cards foretell a detour on your path, indicating a negative outcome to your query. It is important to heed this message and proceed with caution. The currents of the universe are nudging you to pause, reevaluate, and consider alternative routes. Although the answer may be unfavorable, it holds within it the seeds of opportunity. Embrace the lessons embedded in this setback and let them shape a more resilient and informed future. Trust in your ability to navigate the ebbs and flows of life.',
    'The cards have revealed a landscape painted with caution and restraint, indicating a probable negative outcome. It is essential to accept the current limitations and recalibrate your expectations accordingly. This period serves as a valuable lesson in patience and adaptability. Embrace the transformative power of resilience and seek alternative paths that align',
    'The cards whisper a gentle "no" in response to your question. It is a moment of redirection, urging you to reassess your current path. The universe is nudging you to pause, reflect, and realign your intentions. Although the answer may be disappointing, it holds within it the seeds of growth and wisdom. Embrace this moment as an opportunity to gain clarity, make necessary adjustments, and explore new possibilities. Trust that by honoring this message, you will uncover hidden blessings and forge a path that aligns with your highest good.',
    'The cards cast shadows upon the canvas, revealing a negative outcome to your query. It is a time of introspection and recalibration. Embrace this moment as a catalyst for growth and self-discovery. The universe invites you to release attachments to outcomes and surrender to the natural ebb and flow of life. While the answer may be disheartening, it opens the door for new perspectives and fresh beginnings. Trust that by navigating this period with grace and resilience, you will find renewed clarity and navigate towards a more aligned path.'
  ];

  const yesAnswers = [
    "The Magician card represents manifestation, power, and mastery. Its presence suggests a strong 'yes' to your question. The Magician assures you that you have the necessary skills and resources to achieve your desired outcome. It signifies that you possess the ability to make things happen through your focused intention and creativity. Embrace your inner power, harness your talents, and take inspired action to bring about the positive outcome you seek.",
    "The Temperance card represents balance, harmony, and moderation. Its presence suggests a definite 'yes' to your question. This card assures you that by finding equilibrium and taking a measured approach, you will achieve your desired outcome. It encourages patience and the blending of different elements to create a harmonious path towards success. Trust in the process, maintain balance, and navigate with grace as you move towards your goal.",
    "The Chariot represents determination, willpower, and triumph. Its presence signifies a resounding 'yes' to your question. This card assures you that with focused drive and unwavering determination, you will achieve your desired outcome. Embrace your inner strength, harness your ambitions, and move forward with confidence. Victory is within reach; trust in your abilities and navigate any challenges with unwavering resolve.",
    "The Devil represents temptation, bondage, and illusions. In this context, its presence suggests a potential 'no' to your question. It cautions against succumbing to negative influences or being trapped in limiting beliefs. However, it serves as a reminder to break free from destructive patterns and reclaim your power. By recognizing and releasing unhealthy attachments, you can pave the way for positive change and a 'yes' outcome.",
    "The Fool card represents new beginnings, spontaneity, and taking leaps of faith. In this context, its presence suggests a resounding 'yes' to your question. The Fool encourages you to embrace opportunities with enthusiasm and a sense of adventure. It signifies that taking a leap of faith will lead to positive outcomes and growth. Trust in your instincts, follow your heart, and embark on a new journey with confidence.",
    "The Hermit represents introspection, solitude, and inner wisdom. Its presence suggests a 'yes' to your question. This card assures you that by seeking inner guidance and taking time for self-reflection, you will find the answers you seek. Embrace solitude as an opportunity for growth and trust in your inner wisdom. The path to your desired outcome lies within; trust in your own light and follow it with confidence.",
    "The Moon represents intuition, mystery, and hidden knowledge. Its presence suggests a 'no' to your question. It indicates that there may be uncertainties or unseen factors influencing the situation. However, it advises you to trust your instincts and delve deeper for clarity. By navigating through the shadows, you can gain insights that lead to a positive outcome and eventually align with a 'yes' answer.",
    "The Sun card represents joy, positivity, and success. Its presence indicates a resounding 'yes' to your question. It signifies that you are on the right path and will experience happiness and fulfillment in your endeavors. This card assures you that the outcome will be favorable and that you can expect radiant energy and positive outcomes. Trust in your abilities and embrace the light of the Sun as you move forward.",
    "The Tower represents sudden upheaval, unexpected changes, and disruption. However, in this context, its presence suggests a potential 'yes' to your question. It signifies that the current situation or belief system may need to be dismantled for growth and transformation. Embrace the opportunity for change and embrace the unknown. Through the breakdown, you will find a breakthrough and ultimately reach a more favorable outcome."
  ]

const noAnswers = [
    "The Magician represents manifestation, power, and mastery. However, in this context, its presence suggests a potential 'no' to your question. It indicates that the necessary elements may not be aligned at this time. It advises caution in wielding your power and recommends reassessing your approach before moving forward. Take time to refine your skills and gather the resources needed for a more favorable outcome.",
    "Temperance represents balance, moderation, and harmony. Its presence suggests a potential 'no' to your question. It indicates the need for finding equilibrium and avoiding extremes. It advises against rushing or forcing a particular outcome, urging patience and a measured approach. Take time to assess the situation, seek inner balance, and consider alternative paths for a more favorable outcome.",
    "The Chariot represents determination, willpower, and triumph. However, in this context, its presence suggests a potential 'no' to your question. It indicates that the desired outcome may not be achieved through sheer force or control. It advises reassessing your approach and considering alternative paths. Find a balanced and harmonious way forward that aligns with your true intentions for a more favorable outcome.",
    "The Devil represents temptation, bondage, and illusions. Its presence suggests a potential 'no' to your question. It warns against being trapped in unhealthy patterns or negative influences. It advises breaking free from limiting beliefs and releasing attachments that hinder progress. By embracing liberation and making conscious choices, you can overcome obstacles and find a more favorable outcome.",
    "The Fool represents new beginnings, spontaneity, and taking leaps of faith. However, in this context, its presence suggests a potential 'no' to your question. It advises against impulsive actions or rushing into unknown territory. It encourages careful consideration and gathering more information before proceeding. By exercising caution and assessing the risks involved, you can avoid potential pitfalls and navigate towards a more favorable outcome.",
    "The Hermit represents introspection, solitude, and inner wisdom. Its presence suggests a potential 'no' to your question. It advises taking time for self-reflection and seeking clarity within. The Hermit cautions against rushing or seeking external validation. By embracing solitude and inner guidance, you can navigate away from potential pitfalls and find a more favorable outcome.",
    "The Moon represents intuition, mystery, and hidden knowledge. Its presence suggests a potential 'no' to your question. It indicates that there may be uncertainties or hidden factors influencing the situation. It advises caution and further exploration to uncover the truth before proceeding. By delving deeper and seeking clarity, you can avoid potential pitfalls and find a more favorable outcome.",
    "The Sun represents joy, positivity, and success. However, in this context, its presence suggests a potential 'no' to your question. It advises against overly optimistic expectations or being blinded by the light. It encourages a realistic assessment of the situation and potential challenges. By remaining grounded and prepared, you can navigate setbacks and find alternative paths towards a more favorable outcome.",
    "The Tower represents sudden upheaval, unexpected changes, and disruption. Its presence suggests a potential 'no' to your question. It signifies that the current path may lead to unexpected challenges or setbacks. It advises being prepared for major shifts and considering alternative approaches. By embracing adaptability and resilience, you can navigate through turbulent times and find a more favorable outcome."
  ]

  // Export the Yes and No cards
  export { yesCards, noCards, yesAnswers, noAnswers};
  